import classNames from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Navbar } from '@/components/navbar/Navbar';
import  Providers  from '@/components/providers/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html className='h-full' lang='en'>
    <body className={classNames('relative h-full font-sans antialiased', inter.className)}>
      <div className='relative flex min-h-screen flex-col'>
        <Providers>
          <Navbar />
          <div className='flex-1 flex-grow'>{children}</div>
        </Providers>
      </div>
    </body>
  </html>
);

export default RootLayout;
